2020-01-30 15:00:06,322 ERROR: Exception on /edit_profile [POST] [in c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Mikoloth\IdeaProjects\microblogmikko\app\main\routes.py", line 97, in edit_profile
    current_user.set_wotid(form.wotid.data)
  File "C:\Users\Mikoloth\IdeaProjects\microblogmikko\app\models.py", line 123, in set_wotid
    flash(data["account_id"])
KeyError: 'account_id'
2020-01-30 15:01:14,117 INFO: Microblog startup [in C:\Users\Mikoloth\IdeaProjects\microblogmikko\app\__init__.py:83]
2020-01-30 15:02:12,407 INFO: Microblog startup [in C:\Users\Mikoloth\IdeaProjects\microblogmikko\app\__init__.py:83]
2020-01-30 15:02:29,834 ERROR: Exception on /edit_profile [POST] [in c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\mikoloth\ideaprojects\microblogmikko\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Mikoloth\IdeaProjects\microblogmikko\app\main\routes.py", line 97, in edit_profile
    current_user.set_wotid(form.wotid.data)
  File "C:\Users\Mikoloth\IdeaProjects\microblogmikko\app\models.py", line 123, in set_wotid
    flash(data["data"]["account_id"])
TypeError: list indices must be integers or slices, not str
2020-01-30 15:06:16,488 INFO: Microblog startup [in C:\Users\Mikoloth\IdeaProjects\microblogmikko\app\__init__.py:83]
2020-01-30 15:07:21,716 INFO: Microblog startup [in C:\Users\Mikoloth\IdeaProjects\microblogmikko\app\__init__.py:83]
2020-01-30 15:12:32,076 INFO: Microblog startup [in C:\Users\Mikoloth\IdeaProjects\microblogmikko\app\__init__.py:83]
